# Generated by Django 3.0.2 on 2020-05-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=240)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.Categoria')),
                ('sustitutos', models.ManyToManyField(blank=True, related_name='_producto_sustitutos_+', to='mercados.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('edad', models.SmallIntegerField()),
                ('altura', models.SmallIntegerField()),
                ('peso', models.SmallIntegerField()),
                ('objetivos', models.ManyToManyField(blank=True, to='mercados.Objetivo')),
                ('productos_comprados', models.ManyToManyField(blank=True, to='mercados.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_componente',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.Componente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.Producto')),
            ],
        ),
    ]
