# Generated by Django 3.0.4 on 2020-04-28 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alacena',
            name='id',
        ),
        migrations.AlterField(
            model_name='alacena',
            name='numeroRegistro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_Registro', models.DateTimeField(verbose_name='date published')),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('alacena', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercados.Alacena')),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('peso', models.IntegerField(default=0)),
                ('numeroRegistro_alacena', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercados.Alacena')),
            ],
        ),
    ]
