# Generated by Django 2.2 on 2020-05-12 04:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=240)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.Categoria')),
                ('sustitutos', models.ManyToManyField(related_name='_producto_sustitutos_+', to='mercados.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_componente',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.Componente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('edad', models.SmallIntegerField()),
                ('altura', models.SmallIntegerField()),
                ('peso', models.SmallIntegerField()),
                ('objetivos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Alacena',
        ),
    ]
