# Generated by Django 2.2 on 2020-05-12 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0003_remove_usuario_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='objetivos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
