# Generated by Django 3.0.2 on 2020-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0004_usuario_objetivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sustitutos',
            field=models.ManyToManyField(blank=True, related_name='_producto_sustitutos_+', to='mercados.Producto'),
        ),
    ]
