# Generated by Django 3.0.2 on 2020-05-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0005_auto_20200512_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='productos_comprados',
            field=models.ManyToManyField(blank=True, to='mercados.Producto'),
        ),
    ]
